<h1>Google Map</h1>
<div style="height: 400px" id="map"></div>
<script>
    var locations = <?php echo $this->getOffices();?>;
    function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
        });

        var largeInfowindow = new google.maps.InfoWindow();
        var bounds = new google.maps.LatLngBounds();
        var markers = {};

        for (var key in locations) {
            var marker = new google.maps.Marker({
                position: new google.maps.LatLng(locations[key]['lat'], locations[key]['lng']),
                map: map,
                title: locations[key]['name']
            });
            markers[key] = marker;

            marker.addListener('click', function() {
                populateInfoWindow(this, largeInfowindow);
            });

            bounds.extend(markers[key].position);
        }
        map.fitBounds(bounds);
    }

    function populateInfoWindow(marker, infowindow) {
        if (infowindow.marker != marker) {
            infowindow.marker = marker;
            infowindow.setContent('<div>' + marker.title + '</div>');
            infowindow.open(map, marker);
            infowindow.addListener('closeclick',function(){
                infowindow.setMarker = null;
            });
        }
    }
</script>

<script async src="https://maps.googleapis.com/maps/api/js?key=<?php echo $this->getApiKey() ?>&v=3&callback=initMap"></script>


